# Generated by Django 5.0 on 2024-01-10 15:02

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("data_api", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="JejuValuePlace",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("emdNM", models.CharField(max_length=100)),
                ("bsshNm", models.CharField(max_length=200)),
                ("indutyNm", models.CharField(max_length=200)),
                ("rnAdres", models.CharField(max_length=200)),
                ("bsshTelno", models.CharField(max_length=200)),
                ("prdlstCn", models.CharField(max_length=200)),
                ("etcCn", models.CharField(max_length=200)),
                ("regDt", models.CharField(max_length=200)),
                ("laCrdnt", models.CharField(max_length=200)),
                ("loCrdnt", models.CharField(max_length=200)),
                ("dataCd", models.CharField(max_length=200)),
                ("slctnYr", models.CharField(max_length=200)),
                ("slctnMm", models.CharField(max_length=200)),
            ],
        ),
    ]
